export const environment = {
  production: true,
  APP_VERSION: '1.9.4',
  APP_ID: 'NavigatorGuardian',
  TRANSLATION_APP_ID: 'e2f2ecda-b88a-11eb-8529-0242ac130003',
  PARSE_API_PATH: 'guardian/parse',
  API_END_POINT: 'https://gooru.org',
  CLIENT_ID: 'ba956a97-ae15-11e5-a302-f8a963065976',
  CLIENT_KEY: 'c2hlZWJhbkBnb29ydWxlYXJuaW5nLm9yZw==',
  GOORU_TENANT_ID: 'ba956a97-ae15-11e5-a302-f8a963065976',
  TENANT_URL: 'https://tl.gooru.org/',
  TENANT_DOMAIN_NAME: 'tl.gooru.org',
  TEACHER_SIGNUP_URL: 'https://gooru.org/about/navigator/navigator-for-instructors/',
  CDN_URL: 'https://cdn.gooru.org',
  YOUTUBE_IFRAME_API: 'https://www.youtube.com/iframe_api',
  PACKAGE_NAME: 'org.gooru.guardian',
  SHARE_SUPPORT: false,
  SHOW_PUBLIC_CLASS: true,
  APP_LEARNER: false,
  WEB_APP_GUARDIAN_PAGE_URL: 'https://gooru.org/about/navigator/navigator-for-guardians/',
  isDevelopmentMode: false,
  GUARDIAN_API_END_POINT: 'https://guardian.gooru.org',
  EVENT_API_KEY: '33b9ad34-1a0c-43ba-bb9c-4784abe07110',
  SHOW_INTERATIVE: false,
  DISABLE_GPS_MAP_ZOOM: true
};
